# GitHub Pages configuration
title: "vCard - Personal Portfolio"
description: "A modern, responsive personal portfolio website"
url: "https://yourusername.github.io"
baseurl: "/vcard-personal-portfolio"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
author: "Your Name"
email: "your.email@example.com"
twitter:
  username: "yourusername"

# Social links
social:
  - name: "GitHub"
    url: "https://github.com/yourusername"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/yourusername"
  - name: "Twitter"
    url: "https://twitter.com/yourusername"

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/
  - node_modules/
  - package.json
  - package-lock.json
